name: Test Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m install pytest pytest-asyncio
        python -m install -r requirements.txt
        python -m uninstall distribute
        python -m install --upgrade setuptools wheel
        playwright install
    - name: Running tests
      run: |
        HEADLESS=true pytest -s
